/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_point_free: (a: number, b: number) => void;
export const __wbg_get_point_x: (a: number) => number;
export const __wbg_set_point_x: (a: number, b: number) => void;
export const __wbg_get_point_y: (a: number) => number;
export const __wbg_set_point_y: (a: number, b: number) => void;
export const point_create: (a: number, b: number) => number;
export const __wbg_board_free: (a: number, b: number) => void;
export const __wbg_get_board_size: (a: number) => number;
export const __wbg_set_board_size: (a: number, b: number) => void;
export const board_get_data: (a: number) => any;
export const board_size: (a: number) => number;
export const board_score: (a: number, b: number) => number;
export const __wbg_placeerror_free: (a: number, b: number) => void;
export const greet: () => void;
export const version: () => [number, number];
export const init_othello: (a: number) => number;
export const placeable: (a: number, b: number) => number;
export const can_place: (a: number, b: number, c: number) => number;
export const __wbg_scores_free: (a: number, b: number) => void;
export const __wbg_get_scores_black: (a: number) => number;
export const __wbg_set_scores_black: (a: number, b: number) => void;
export const __wbg_get_scores_white: (a: number) => number;
export const __wbg_set_scores_white: (a: number, b: number) => void;
export const count_score: (a: number) => number;
export const place_at: (a: number, b: number, c: number) => [number, number, number];
export const generate_ai_play: (a: number, b: number, c: number) => number;
export const score: (a: number, b: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
