name: Root CI
on:
  pull_request:
  push: { branches: [main] }

jobs:
  lint:
    name: "Lint via Biome"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: biomejs/setup-biome@v2
      - run: biome check
  fmt:
    name: "Format via Prettier"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: "pnpm@9.12.2"
      - run: pnpm install --frozen-lockfile
      - run: pnpm prettier . --check
