name: WASM CI
on:
  pull_request:
  push: { branches: [main] }

defaults:
  run:
    working-directory: ./wasm
env:
  RUSTFLAGS: -Dwarnings
jobs:
  build:
    name: "Build with wasm-pack"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/cache@v4
        with:
          path: |
            wasm/target
          key: cargo-cache-${{ github.job }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 0.13.0
      - run: wasm-pack build --release
      - run: test `git diff | wc -l` == 0 # wasm/pkg must align with src
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/cache@v4
        with:
          path: |
            wasm/target
          key: cargo-cache-${{ github.job }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test --all-features
      - run: cargo clippy
