name: Web CI
on:
  pull_request:
  push: { branches: [main] }
defaults:
  run:
    working-directory: "web"

jobs:
  check:
    name: "Build, check and more: depends on wasm"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: jetli/wasm-pack-action@v0.4.0
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/cache@v4
        with:
          path: |
            wasm/target
          key: cargo-cache-${{ github.job }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - run: wasm-pack build --target web
        working-directory: wasm
      - run: cp -r ../wasm/pkg src/wasm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run check
      - run: pnpm run build
